// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  alternating_can: dynamic(() => import("./AlternatingCan")),
  big_text_view: dynamic(() => import("./BigTextView")),
  carousel: dynamic(() => import("./Carousel")),
  contact_us: dynamic(() => import("./ContactUs")),
  gallery: dynamic(() => import("./Gallery")),
  hero: dynamic(() => import("./Hero")),
  sky_dive: dynamic(() => import("./SkyDive")),
};
